version: '3.7'

services:
  nextcloud:
    image: nextcloud:18
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - nextcloud
    volumes:
      - nextcloud-vol:/var/www/html
  cron:
    image: nextcloud:18
    restart: unless-stopped
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
      - mysql
    networks:
      - nextcloud
    volumes:
      - nextcloud-vol:/var/www/html
  mysql:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - nextcloud
    volumes:
      - mysql-vol:/var/lib/mysql
  redis:
    image: redis:5
    restart: unless-stopped
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - nextcloud
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-vol:/data
  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      - JWT_ENABLED
      - JWT_SECRET
    networks:
      - nextcloud
    volumes:
      - onlyoffice-log:/var/log/onlyoffice
      - onlyoffice-lib:/var/lib/onlyoffice
      - onlyoffice-data:/var/www/onlyoffice/Data
      - onlyoffice-db:/var/lib/postgresql
      - onlyoffice-fonts:/usr/share/fonts/truetype/custom
      - onlyoffice-redis:/var/lib/redis
      - onlyoffice-rabbitmq:/var/lib/rabbitmq
  preview-generator:
    image: cedrichopf/preview-generator:latest
    build: ./preview-generator
    restart: unless-stopped
    depends_on:
      - nextcloud
      - mysql
    environment:
      - GENERATOR_ENABLED
      - GENERATOR_CRON
    networks:
      - nextcloud
    volumes:
      - nextcloud-vol:/var/www/html

networks:
  nextcloud:
    external: false

volumes:
  nextcloud-vol:
  mysql-vol:
  redis-vol:
  onlyoffice-log:
  onlyoffice-lib:
  onlyoffice-data:
  onlyoffice-db:
  onlyoffice-fonts:
  onlyoffice-redis:
  onlyoffice-rabbitmq:
